title: X Feed Filter
email: mertegithub@gmail.com
description: >-
  Browser extension for Twitter/X — blocks or hides posts from specific Communities to keep your timeline clutter‑free.
baseurl: "/x-feed-filter" # the subpath of your site, e.g. /blog
url: "https://merteraslan.github.io" # the base hostname & protocol for your site
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude these files/folders from the generated site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 