source "https://rubygems.org"

# Jekyll core
gem "jekyll", "~> 4.3.2"

# Jekyll plugins (add any that are in your _config.yml)
gem "jekyll-feed", "~> 0.17"
gem "jekyll-seo-tag", "~> 2.8"
# gem "jekyll-sitemap", "~> 1.4"
# gem "jekyll-paginate", "~> 1.1"
# gem "jekyll-archives", "~> 2.2"

# Windows support
gem "wdm", ">= 0.1.1", :platforms => [:mswin, :mingw, :x64_mingw, :jruby]

# Standard library gems required for Ruby 3.4+
gem "csv"
gem "logger"
gem "base64" 